name: movie_project
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  logger: ^2.5.0
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.6
  auto_route: ^10.1.0+1
  auto_route_generator: ^10.1.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.12
  email_validator: ^3.0.0
  fluttertoast: ^8.2.12
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_launcher_icons: ^0.14.4
  auto_size_text: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  


flutter:

  uses-material-design: true

  assets:
    - lib/assets/




  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

flutter_native_splash:
  image: lib/assets/diziGoIcons.png
  color: "#000000"
  android: true
  ios: true
  android_12:
    image: lib/assets/diziGoIcons.png
    color: "#1B1139"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/diziGoIcons.png"
  min_sdk_android: 21    